HPCC-13496 Fix compilation Error: 'this' pointer and references cannot be null
- IAtom: Remove multiple aliases to access getNamePtr() from IAtom
- Add global str(IAtom *) function to safely access getNamePtr() even if IAtom * argument is null
- IIdAtom: Remove multiple aliases to access getNamePtr() from IAtom
- Add global str(IIdAtom *) function to safely access getNamePtr() even if IIdAtom * argument is null
- Replace all usages of the aliases removed previously with a call to the newly create str() function
- IIdAtom: remove the lower() member variable and replace with global lower(IIdAtom *p) function
- Modify cmake commonSetup.cmake to have this==null treated as compilation errors by CLang compilers