HPCC-23757 Undefined reference to vtable build error
Remove ESP service ws_configmgr from the build, no longer needed

Signed-off-by: Ken Rowland <kenneth.rowland@lexisnexisrisk.com>