HPCC-13496 Fix compilation Error: 'this' pointer and references cannot be null
- getNamePtr() in IIdAtom and IAtom class renamed to queryStr()
- directly call queryStr() member function  of IIdAtom and IAtom
instead of using str when object known to be non-null
- fix where *str() used when str() should have been fixed
- use lower(id) instead of "id ? id->queryLower() : NULL; "
- Replace tabs with spaces