HPCC-13496 Fix compilation Error: 'this' pointer and references cannot be null
Modfiy v8embed.cpp to use the global str() function instead of IAtom:str()