HPCC-26543 Fix spacing regression in labels.helmVersion
Caused helm install:
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Service.metadata): unknown field "lables" in io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta

also add labels.helmVersion to other places we create Service
manifests

Signed-off-by: Jake Smith <jake.smith@lexisnexisrisk.com>