Revert "HPCC-13496 Fix compilation Error: 'this' pointer and references cannot be null in well-defined C++ code"
This reverts commit 55a5df03b607f7a5b2d9ddb29f459afa93825af9.